app:
  name: "spring-cloud-config-client.local"
  website: "http://reactivetick-09999.com"
  message: "Hello from Spring Config Server"
config:
  profile: "local"
server:
  port: 8082
message: "Hello from Spring Config Server"  
